import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import CapturePhoto from '@/components/CapturePhoto/CapturePhoto'

const inter = Inter({
	subsets: ['latin'],
	weight: ['400', '500'],
	variable: '--font-inter',
})

export default function Home() {
	return (
		<>
			<Head>
				<title>Zdrowe Info</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<h1>zdrowe info</h1>
				<button>jakiśbutton do aparatu</button>
				<p>nie wiem pomyśl</p>

				<CapturePhoto />
			</main>
		</>
	)
}
